### ISSUE TITLE
Should installationID be required?

### ISSUE THREAD

**Issue by cfjedimaster** [drudge/node-tidbyt#3]
I notice that installationID is required, but doesn't the API let you push an image without an installation value? For ad hoc messages for example.

**Comment by drudge** [comment]
The installationID is not required to push:
https://github.com/drudge/node-tidbyt/blob/main/index.js#L317-L328

**Comment by cfjedimaster** [comment]
Maybe I did something wrong, but it didn't work until I did:

```js
await device.push(Buffer.from(img_data), {
  installationId:'Custom',
  background:false
});
```

**Comment by drudge** [comment]
I'm leveraging no installation + background: false in both my Homebridge plugin and the new n8n node to deliver transient notifications to my Tidbyt devices.

One thing to note that if an installation ID is not specified, it will be shown immediately but will only be shown on device a single time. Perhaps you missed it?

**Comment by cfjedimaster** [comment]
Well shoot, not sure what went wrong back when I first tried, but it's working fine now w/o. I *swear* it was giving errors about the installationID. :) Happy to be wrong though!

**Comment by drudge** [comment]
Glad it's working for you now!
